### PR TITLE
Annotate type for ariaActiveAttribute

### PR DESCRIPTION
**Pull request by rictic**
Appeases the compiler.

### CODE REVIEW

**Comment by notwaldorf** [comment]
@rictic Hmm, that's weird. The property is defined in the behaviour, we're just changing its default value. Why do we need to redefine its type here? 😟

**Comment by rictic** [comment]
¯\_(ツ)_/¯ it's a mystery to me.

**Comment by notwaldorf** [comment]
@jklein24 Halp? Any ideas why this is a thing? 🙈

**Comment by jklein24** [comment]
Yep! The first reason is my own laziness... The compiler pass doesn't trace all the types of properties in this way all the way up the chain of behaviors. It could, but it would take some refactoring. The other reason is semantic nitpicking. To me, anything in the properties block should be considered a declaration and should have a type, even if it's only to make developers reading the code a bit more clear on where properties come from. If just the default value is being overridden, is there any reason not to do this change in a lifecycle method instead of the properties block? Will that trigger extra change listeners or something else that's undesirable?

**Comment by notwaldorf** [comment]
@jklein24 Oh, I don't. Thing of preference, I guess. It's totally fine to add the type, I just thought :sparkles: something-something-magic-behaviours :sparkles:. No worries! Merging this!

**Comment by jklein24** [comment]
> :sparkles: something-something-magic-behaviours :sparkles:

Is how I intend to answer all questions on our mailing lists from now on :-).

**Pull request merged**
