### PR TITLE
apply --paper-font-common-base

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Applies `--paper-font-common-base` to the host.

This is part of the effort of applying `Roboto` font to all the paper elements http://jsbin.com/mumovix/1/edit?html,output

### CODE REVIEW

**Comment by valdrinkoshi** [comment]
@notwaldorf kindly review

**Comment by notwaldorf** [comment]
lgtm

**Comment by notwaldorf** [comment]
As talked offline, I think this PR should only apply the mixin, and not import the font.

**Comment by valdrinkoshi** [comment]
@notwaldorf PR updated :+1:

**Comment by notwaldorf** [comment]
LGTM 🌵

**Comment by valdrinkoshi** [comment]
Putting it in `:host` makes it easier to override the font without mixins because the selector is "weaker". E.g. here it can be overridden with the `*` selector http://jsbin.com/dutoyov/1/edit?html,output

**Comment by valdrinkoshi** [comment]
As agreed offline, we leave it in the host for now, since it produces the same result.
Will update the doc with
> This element applies the mixin `--paper-font-common-base` but does not import `paper-styles/typography.html`.
In order to apply the `Roboto` font to this element, make sure you've imported `paper-styles/typography.html`.

**Comment by valdrinkoshi** [comment]
@notwaldorf update done, this is how the styling paragraph now looks:
screen shot 2016-01-22 at 12 24 39 pm

**Comment by notwaldorf** [comment]
👍

**Pull request merged**
