### PR TITLE
GPU animated checkbox

### LINKED ISSUE #71: 0 transform3D hack on chekcboxContainer
Hello,

is there any reason to have a translateZ(0) on the checkbox container ? It creates a layer that needs compositing and might affect our goal of 60 fps on mobile devices.

Thanks

### PR DESCRIPTION
**Pull request by hypnoce**

### CODE REVIEW

**Comment by hypnoce** [comment]
From my perspective, the resulting visual effect should be unchanged but you may want to check yourself to be sure.

**Comment by notwaldorf** [comment]
I kind of wish this PR was actually split in two. I don't have a problem with removing the `translateZ`, since that makes sense, but now you've also changed the way the checkbox is animated, which means that if it is working differently, this will be harder to revert. Also, I'm not super sure about the motivation of the second change -- is it just to clean up the code? How can you guarantee they look the same? :(

**Comment by hypnoce** [comment]
You are right, I made another PR for the translateZ.
Regarding this pull request, it is only to assure that the animation is totally done on the GPU. IT really helps on mobile devices.
Nevertheless, I will investigate more about the changes in the way the checkbox is animated.

**Comment by hypnoce** [comment]
Hi,

you were right, the animation was modified a lot. I think this new version is better but it does not exactly animates like before.
Here is an alternative version with the slight translation : https://github.com/hypnoce/paper-checkbox/tree/gpu-acceleration-animation-with-translation
Those two versions are not perfect but they both animate fully on the GPU. I gives a smoother effect on our mobile webapp.

**Comment by MartinMoizard** [comment]
lgtm

**Comment by hypnoce** [comment]
Hi,
did you get a chance to review this PR ? We are still depending on the forked branch and it would be great to switch back to the offical release.
Thanks

**Comment by notwaldorf** [comment]
This looooks about right to me (I've been checking a zoomed-in checkbox for 10 minutes), but I'm going to ask @frankiefu to double check that the CSS makes sense

**Comment by hypnoce** [comment]
Haha I did the same thing... in slow motion.

**Comment by notwaldorf** [comment]
I'm going to merge this. I think it looks good, and we can fix things in the future if anyone spots any differences. Thanks!

**Comment by hypnoce** [comment]
:+1:

**Pull request merged**
