### PR TITLE
🍕 Add checkbox size var

### LINKED ISSUE #59: Expose a sizing variable
Right now, the checkbox size is hardcoded to 18px.
It would be nice to expose a size variable somehow, maybe with `calc` for the other elements that comprise the checkbox to adjust to user given sizes.

### PR DESCRIPTION
**Pull request by samccone**
Fixes #59

---

screen shot 2015-09-02 at 4 59 22 pm

### CODE REVIEW

**Comment by notwaldorf** [comment]
@samccone I think the ripple is the wrong size though :(

**Comment by samccone** [comment]
oh shucks :cry:

**Comment by samccone** [comment]
word word @notwaldorf so the ripple centering was simple enough... however I have run into an interesting issue with a `var(` inside of a `calc` .. inside of a `@keyframes` ... it looks like it is not being translated at all.. which makes moving the  check box to the center difficult (see impossible) since the position of the checkbox is being set "finally" via the animation. :game_die: 

Any thoughts on this?

**Comment by notwaldorf** [comment]
Gonna throw @sorvell at this one and see what he says :balloon:

**Comment by sorvell** [comment]
Polymer's custom properties cannot currently be consume in @keyframe rules. Filed https://github.com/Polymer/polymer/issues/2399 to track progress on fixing this.

**Comment by notwaldorf** [comment]
@samccone Doing some cleanup -- can I close this PR until the Polymer fix is ready, and then you can maybe re-open it/re-visit then?

**Comment by samccone** [comment]
:+1: sgtm can we xlink in the polymer issue back so we do not forget:) :thought_balloon:

**Comment by notwaldorf** [comment]
Done!

**Pull request closed without merging**
