### PR TITLE
Fixes #139: Use SVG to draw the checkmark.

### LINKED ISSUE #139: Checkmark off-center and jittery at non-default sizes
Demo: https://jsfiddle.net/wzse6m00/2/

When `paper-checkbox`es are sized other than the default 18px, the checkmarks may be off-center. When a `paper-checkbox`'s container is resized (e.g. when resizing the page), the checkmark jumps around, stretches, and shrinks, making it extremely jittery.

Tested with Chrome 52 and 53 and Edge.

May be related to the root cause of #130, but neither c656a41 nor #129 fix this issue.

### PR DESCRIPTION
**Pull request by bicknellr**
Go to either demo below and resize the window to see the difference:

before: http://jsbin.com/fepide/1/edit?html,output
screen shot 2016-07-20 at 17 46 17

after: http://jsbin.com/lisubu/1/edit?html,output
screen shot 2016-07-20 at 17 46 24

(Fixes #139.)

### CODE REVIEW

**Comment by abdonrd** [comment]
Why not use the `icon-icons` "`check`" icon?

**Comment by bicknellr** [comment]
@abdonrd good idea! I rather not make paper-checkbox depend on iron-icon but it's definitely a better source for the SVG than trying to roll my own.

**Comment by abdonrd** [comment]
@bicknellr why not use the `iron-icon` element?

**Comment by bicknellr** [comment]
@rictic

**Comment by bicknellr** [comment]
@cdata is it ok if I assign this to you?

**Comment by danbeam** [comment]
yo, what's the status on this?

**Comment by dima-gorskov** [comment]
When merge this PR?

**Comment by e111077** [comment]
This visual change will cause quite a bit of jank between the old and new versions which would break a lot of visual tests.



I'm for SVGification, but on the fence about the recentering (as it's non-standard as is).

Thoughts @notwaldorf @rictic?

**Comment by e111077** [comment]
Would like to know how this PR fares in our internal tests.

**Comment by notwaldorf** [comment]
(going to remove myself as a reviewer since I think Elliott is on this!)

**Comment by e111077** [comment]
@bicknellr any updates on internal testing?

**Comment by bicknellr** [comment]
Last I checked, it breaks a bunch of screenshot tests - as expected. I don't remember there being any obviously broken non-screenshot tests but I should run it again.

**Pull request closed without merging**
